package mensajes;

public enum MensajeType {
	//Usados por cliente
	CONEXION, //0
	LISTA_USUARIOS, //1
	PEDIR_FICHERO,//2
	PREP_CLIENTESERVIDOR,//3
	CERRAR_CONEXION,//4
	
	//Usados por Servidor
	CONFCONEXION,//5
	CONFLISTA_USUARIOS,//6
	EMITIRFICHERO,//7
	PREP_SERVIDORCLIENTE,//8
	CONFCERRARCONEXION,//9 
	ENVIO,//10
	ARCHIVO_INEXISTENTE;//11
}
